spring:
  application:
    name: book-service
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
      discovery:
        enabled: true
        service-id: config-server1
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: amigoscode
      port: 27017
      host: 192.168.99.102
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 8081

